baseurl = "https://bucciaratimes.netlify.app/"
languageCode = "ja"
defaultContentLanguage = "en"
title = "BucciaraTimes"
theme = "dream"
copyright = '©️2020 Bucciarati All Rights Reserved'

# googleAnalytics = ""

disqusShortname = "Bucciarati"

enableRobotsTXT = true

hasCJKLanguage = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  # background = "#dddddd"
  # backgroundImage = "/me/background.jpg"
  backgroundImage = "/images/totoro024.jpg"
  linkColor = "seagreen"

  # dark mode 

  defaultDark = true
  # backgroundDark = "black"
  backgroundDark = ""

  # backgroundImageDark = "/me/background-dark.jpg"
  backgroundImageDark = "/images/totoro042.jpg"

  darkLinkColor = "skyblue"
  darkNav = true
  dark404 = true

  images = ["/images/totoro024.jpg"]

  author = "Bucciarati"
  description = "Bucciaratimes is weblog site about Football, especially Argentina & Barcelona"
  avatar = "/images/author.jpg"
  headerTitle = "Bucciarati"
  motto = "I'm 22. Football Lover in Japan."
  categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  # utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "bucciaratimes@gmail.com"
  twitter = "@BucciaraTimes"
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = "favicon_io"

  siteStartYear = 2020

  favicon = "/images/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  hasTwitterEmbed = true

[params.advanced]
  customCSS = ["css/custom.css"]
  customJS = []

